### ISSUE TITLE
GET /tasks/{taskId} のようなエンドポイントを追加しようとした時にファイル構成はどうなりますか？

### ISSUE THREAD

**Issue by podhmo** [budougumi0617/go_todo_app#21]
おそらくchi.URLParam()的なものを扱う必要が出てきて、handlerのテスト時にもchi.Routerが必要になると思うのですが、その辺をどうハンドリングするだろう？ということが気になりました。

あるいはGETではなくてもstatusを更新するようなAPIでも良いです (PATCH?)

**Comment by podhmo** [comment]
https://github.com/podhmo/go_todo_app/pull/1/files/9b49d067dfaf53751993c4516dbc71439a2d6139..88e2443a12d9fd187ebf9c2395164bc1d4786d48

例えば、`PATCH /tasks/{id}` を実装してみたPRです。ここのhandlerのテストコードがmux.goでのpathの定義を参照したくなります。

**Comment by budougumi0617** [comment]
問題提議ありがとうございます！週明けまでに回答用意します！
（正解はないのであくまで私だったらこうする、という案ですが）

**Comment by budougumi0617** [comment]
サンプルコードまで書いていただきありがとうございます！zenn bookで補遺（追加の章）書くときにこのトピックも触れたいと思います！

HTTPハンドラーのテストコードはサンプルコードに書いていただいたとおりの書き方を私もしています。
https://github.com/podhmo/go_todo_app/blob/88e2443a12d9fd187ebf9c2395164bc1d4786d48/_chapter_ex/handler/change_task_status_test.go#L67-L73 
```go
			sut := ChangeTaskStatus{
				Service:   moq,
				Validator: validator.New(),
			}
			router := chi.NewRouter()
			router.Patch("/tasks/{id}", sut.ServeHTTP)
			router.ServeHTTP(w, r)
```

私の経験だと2つのアプローチをとったことがあります。

- 解釈で割りきる
- 各エンドポイントはPATHの定義とHTTPハンドラーの実装を含む構造体を用意する簡易フレームワークを作る

**Comment by budougumi0617** [comment]
解釈で割り切るパターンは次のように解釈してハンドラーのテストコード中のpathの定義と実際のmuxのpathの定義が乖離しても諦める考え方です。

- HTTPハンドラーのテストコードは書いていただいたテストコードにする
- HTTPハンドラーのテストコードでは次のように考える
  - HTTPハンドラーの実装が期待通りにpathを解釈できていればよい
  - mux側でどのようにpathが定義されるかは関知しない。それはHTTPハンドラーの責務ではないので、テストコードでもそれを考えないのは問題ない（と解釈する）
  - 「muxが正しくHTTPハンドラーの実装を呼び出している」ことをmux側の実装の責務とする
    - mux側のテストコード（あるいはE2Eテストコード）で「HTTPハンドラーの実装が正しく実行されること」を検証する

**Comment by budougumi0617** [comment]
もう一つの案は実装を見てもらったほうがわかりやすいのですが、interfaceを切ってpathの定義とHTTPハンドラーの実装を合わせるやり方です。

```go
// Path定義の責務をMuxの初期化ロジックからHTTPハンドラーの実装側に寄せるためのinterface。
// chi.Mux.Routeメソッドなどを使いたいならばもう少し手の混んだ定義が必要になる
type Handler interface {
	ServeHTTP(w http.ResponseWriter, r *http.Request)
	Method() string
	Path() string
	// 真面目にやるとハンドラーごとに異なるミドルウェアの設定をするために Middleware() http.Hanlder も必要になる
}

// muxの初期化時は mux.MethodFunc(h.Method(), h.Path(), h.ServeHTTP) のように利用する
```

muxの初期化時に行なうpathの定義も Handler インターフェイスから取得するようにします。これならばmux.go（muxの初期化を行なう実装部分）からHandler インターフェイスを満たす実装側にpathを定義する責務が移せるかなと思っています。

具体的な実装は↓になります。
https://go.dev/play/p/gS-kZKiyY_Q

サンプルコードにコメントしたとおり、ルーティングフレームワークの機能をもっと使うためにはもう少しinterfaceの定義を考える必要があります。gorilla/muxで似たようなinterfaceを使っているときは結構割り切って使っていました。

独自インターフェイスを定義して簡易フレームワークを作るこの案は「私のやりかた」を読者に押し付ける気がして書籍内ではやりませんでした（「私のやりかた」をハンズオン内で解説するのもなあ…というところもあり）

**Comment by podhmo** [comment]
なるほど、詳細な回答ありがとうございます。

ついでなので自分の回答も載せておくと、handlerのパッケージ毎にmount.goのようなファイルを作りそこでroutingの設定をしてしまい、テスト時にはhandlerとrouterを密結合させてテストしちゃうことが多いですね。

- https://togithub.com/go-chi/chi/issues/478

疎結合を頑張りたいときにこのmountの引数がどんどん増えていくのが辛いですが、ユニットテストと言いつつrouterとは結合した状態です。

**Comment by podhmo** [comment]
> 独自インターフェイスを定義して簡易フレームワークを作るこの案は「私のやりかた」を読者に押し付ける気がして書籍内ではやりませんでした（「私のやりかた」をハンズオン内で解説するのもなあ…というところもあり）

わかります 👍

**Comment by budougumi0617** [comment]
コメントまでありがとうございます！！なるほどそのようなやりかたも！
