### ISSUE TITLE
golangci-lintの設定でdeprecatedの警告が出るようです。

### ISSUE THREAD

**Issue by nnabeyang** [budougumi0617/go_todo_app#70]
ローカルでもlintのチェックした方が良いなと思い、実行してみたところ、次のような警告が出ました。
```
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
警告に書かれているように`.golangci.yml`の`deadcode`を`unused`にすると解消しました。

**Comment by nnabeyang** [comment]
unusedはdeadcodeと同等ではないようで、unusedの場合はexportedな関数であれば呼び出しが無くても警告は出ないようです。

**Comment by budougumi0617** [comment]
サンプルコードの設定ファイルを修正しておきました、ありがとうございました！

- https://github.com/budougumi0617/go_todo_app/releases/tag/v1.0.9

**Comment by nnabeyang** [comment]
@budougumi0617 まだ以下の箇所にdeadcodeが残っているのですが、これはそのままで問題無いでしょうか?

https://github.com/budougumi0617/go_todo_app/blob/main/_chapter15/section59/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter16/section60/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter16/section61/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter16/section62/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter16/section63/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter16/section64/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter17/section68/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter17/section70/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter18/section74/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter19/section75/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter19/section78/.golangci.yml#L13
https://github.com/budougumi0617/go_todo_app/blob/main/_chapter19/section79/.golangci.yml#L13

**Comment by budougumi0617** [comment]
以下の理由より参考コードの修正はしないつもりです 🙏 

- 実行が失敗する類の致命的なものではない
- 依存ライブラリのバージョンアップの対応をはじめると時間の経過とともにどんどん追加対応が必要になってしまう

**Comment by nnabeyang** [comment]
@budougumi0617 了解しました。ご対応いただきまして、ありがとうございました。
