### ISSUE TITLE
[Question]mux_test.goは19章で削除すべきファイルでしょうか？

### ISSUE THREAD

**Issue by mom0tomo** [budougumi0617/go_todo_app#83]
P162 `「httptest」パッケージを使ったテスト` の項で、mux_test.goが追加されています。19章でルーティングに変更を加えるとこのテストが落ちるようになります。サンプルコードのリポジトリを見たところ、19章のディレクトリには該当ファイルが存在しませんでした。
https://github.com/budougumi0617/go_todo_app/tree/main/_chapter19

こちらについては19章でルーティングを変更する際に削除するとよいでしょうか？
cc: @mi-bear

**Comment by budougumi0617** [comment]
ご指摘のとおりです！正誤表にmux_test.goを削除する旨を追記しました。ありがとうございました！！

- https://github.com/budougumi0617/go_todo_app/releases/tag/v1.0.13
